### ISSUE TITLE
Quick menu save bug

### ISSUE THREAD

**Issue by BobbyTheBuildery** [RedShyGuy/Vapecord-ACNL-Plugin#109] opened 2022-07-15 12:03 UTC
When you have save/restore bound to the quick menu and you save it will save but then you will be stuck with a black box on the top screen. 
Crash dump: [crash_dump_00000008.zip](https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/files/9120580/crash_dump_00000008.zip)

**Comment by RedShyGuy** [comment] 2024-08-21 12:07
Can't reproduce, closing this

**Closed by RedShyGuy** 2024-08-21 12:07 UTC
