### ISSUE TITLE
bug net fails to work when movement speed multiplier is enabled

### ISSUE THREAD

**Issue by Argoneon1810** [RedShyGuy/Vapecord-ACNL-Plugin#140] opened 2023-10-24 15:55 UTC
I don't know if you are in charge of individual cheats or the plugin itself only, but since this page looks most fitting to this issue, I leave it here.

I visited tortimer island to catch sharks, and I realised, with movement speed multiplier set, swing animation of bug net is not fully done, and any insects, including anything that optically seems to hit the net, fails to be caught.

disabling this cheat and reloading the island by going in and out to the hut make the net back to working state.

**Comment by Argoneon1810** [comment] 2023-10-24 18:53
device: 2DS XL
game: ACNL WA (KOR) v1.5

**Comment by FoofooTheGuy** [comment] 2023-11-13 20:00
Since I couldn't reproduce this on the latest commit, this has been fixed and will be in the next release

**Closed by FoofooTheGuy** 2023-11-13 20:00 UTC
